[package]
name = "llmtool_client"
version = "0.1.0"
authors = ["voidKandy <voidkandy@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.6.0", features = ["fullstack"] }
tracing = "0.1.41"
reqwest = "0.12.12"

candle-core = "0.8.3"
candle-nn = "0.8.3"
candle-transformers = "0.8.3"
serde = { workspace=true }
serde_json = { workspace=true }
# Must use this version with default_features off otherwise the build will fail
tokenizers = { version = "0.19.0", default-features=false, features = ["unstable_wasm"] }
chrono = { version = "0.4.40", features = ["serde"] }
dioxus-sdk = { version = "0.6.0", features = ["storage"] }


[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
# mobile = ["dioxus/mobile"]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

# [profile.android-dev]
# inherits = "dev"
