[package]
name = "llmtool"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
[workspace]
members = ["client", "server"]

[workspace.dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.140"

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
